name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up openJDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      # run tests and jacoco coverage report
      - run:
          name: Gradle build
          command: ./gradlew clean build jacocoTestReport

      # set up xml path for code climate
      - run:
          name: Set jacoco.xml path for code climate
          command: JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco

      # upload coverage on code climate
      - run:
          name: Upload code climate report
          command: ./cc-test-reporter upload-coverage -r $TEST_COVERAGE
          when: on_success